### ISSUE TITLE
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #3 'index'

### ISSUE THREAD

**Issue by krishnats98** [GauthierDmn/question_generation#9]
Hi , I am getting error while executing eval.py

8431it [00:10, 836.27it/s]
Traceback (most recent call last):
  File "eval.py", line 81, in <module>
    pred = model(sentence, len_sentence, answer=answer)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/project/model.py", line 29, in forward
    enc_output, enc_hidden = self.enc(sentence, sentence_len, answer)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/project/layers.py", line 49, in forward
    x = self.embedding(x, y)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/project/layers.py", line 19, in forward
    emb = self.w_embed(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/sparse.py", line 117, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1506, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #3 'index'

anyone please help

**Comment by khushgrover** [comment]
Hey, did your Runtime Error got solved? Please could you share you?

**Comment by khushgrover** [comment]
Hey, did your Runtime Error got solved? Please could you share how?

**Comment by khushgrover** [comment]
did your issue get solved?
